name: Codecov workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Code
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: 60411876-3693-4fe8-9a1f-8245d9255c1a
          slug: aoeai/aoeai-interstellar-navigator-android
#1