name: Workflow for Codecov example-android
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Set up Android SDK
        uses: actions/setup-android@v2
        with:
          sdk-version: '31.0.0'
      - name: Build and test Android app
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug test
      - name: Run ATS
        uses: codecov/codecov-ats@v0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Run tests and collect coverage
        run: ./gradlew jacocoTestReport
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4-beta
        with:
          flags: smart-tests
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}